name: build

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master
  schedule:
    - cron: '0 6 * * 1' # weekly (every monday at 6 am UTC)

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: setup DepotDownloader
        shell: bash
        run: |
          mkdir depotdownloader
          cd depotdownloader
          curl -L 'https://github.com/SteamRE/DepotDownloader/releases/download/DepotDownloader_2.5.0/depotdownloader-2.5.0.zip' > depotdownloader.zip
          unzip depotdownloader.zip

      - name: setup Space Engineers
        shell: bash
        run: |
          echo 'regex:^DedicatedServer64/' > filelist.txt
          # https://steamdb.info/app/298740/depots/
          depotdownloader/DepotDownloader.exe -app 298740 -depot 298741 -filelist filelist.txt -dir .
          mv DedicatedServer64 .GameBinaries

      - name: setup dotnet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: build
        run: dotnet build --configuration Release
